### ISSUE TITLE
Figure out error handing, retry strategy 

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#101]
In the event of the client receiving an error from the server, we need to attempt to retry. The error could be a fluke, or it could be symptomatic of something bigger. 

If retries aren't working, we should discuss other ways to indicate to the user that the service isn't working.

**Comment by EvanHahn** [comment]
Here's what I'm thinking:

When making an API request, if the request fails, throw an error with the status code. (We currently throw a string.) If the request totally failed (e.g. the user has no connection), we'll also throw, but without a status code.

If the status code is empty (e.g., a network failure) or any of 408 413 429 500 502 503 504 521 522 524, retry with exponential backoff for up to a minute. (I stole these status codes from [Got](https://www.npmjs.com/package/got#retry).) After that, display an error to the user.

If the request uses `useSWR`, we can use its [`onErrorRetry`](https://swr.vercel.app/docs/error-handling#error-retry) feature to help.

How does that sound?

**Comment by kevincianfarini** [comment]
Love it! We need to do some thinking about error handling with the `/send-email` endpoint. Its not transactional, so it's possible that it could partially fail. ( eg. Send 2/3 emails, error with a 500).

**Comment by kevincianfarini** [comment]
We could potentially "supervise" sending individual emails and send down an error body that explains which emails failed. That way, we know which ones we need to retry for.

**Comment by kevincianfarini** [comment]
I can read into that, i haven't heard of it before. Ill let you know later this weekend!

**Comment by kevincianfarini** [comment]
@jacknugent is exponential backoff used currently? 

@EvanHahn or @jacknugent, the `/send-email` API will currently respond with the failed bioguide IDs in an error scenario. 

> For something like sending an email, the front-end could also parse the error for the list of failed emails, and display something to the user like "2/3 emails sent, click to retry"

I really like this idea. Can we make it happen? In this scenario, we should specify that the request failed though, and not that we just decided to send 2/3 emails because we were too lazy to send the last one.

**Comment by EvanHahn** [comment]
To me, it feels like we should repeatedly try to get to 3/3 emails sent (or whatever the total is) until we eventually give up and let the user manually retry again.

Alternatively, the server could enqueue a job to send them, so even if the user closes the browser window the email would still go through.

Just some musings—not necessarily a well-considered strategy.

**Comment by kevincianfarini** [comment]
@EvanHahn Sure, I agree to an extent. 

We could retry sending the emails 3 times until completion. If at that point we haven't succeeded, then we should inform the user. 

@mcchang and I considered queuing, but that's going to be a task for later.

**Comment by jacknugent** [comment]
Is this closed? I added retrying for send-email

**Comment by jacknugent** [comment]
Closing with PR #172
