### ISSUE TITLE
Redesign representative cards

### ISSUE THREAD

**Issue by jacknugent** [climatechangemakers/climate-changemakers-act#104]
New design on [figma](https://www.figma.com/file/PEEkfIkziGfLogDHxSex9K/CC-%2F%2F-Action-Tool?node-id=540%3A517):
<img width="583" alt="image" src="https://user-images.githubusercontent.com/31449177/136126564-eb162f63-52f3-466e-8732-25383a4a7241.png">

**Comment by jacknugent** [comment]
If it's non-trivial, I don't think it's a big deal to keep as shortname

**Comment by kevincianfarini** [comment]
Good catch, I didn't think about that. I'll remain open to implementation changes until we hear back from the designer.
