### ISSUE TITLE
More inputs when sending email

### ISSUE THREAD

**Issue by jacknugent** [climatechangemakers/climate-changemakers-act#116]
Currently send email has smaller inputs (prefix, first name, last name, letter topic, subject) and one long input (body). I know Eliza mentioned maybe some other smaller inputs to help guide the user and personalize their email such as "Tell your rep where you're from" and "What do you do?"

Right now the design has room for them (notice the gap above "Draft Your Email")

![image](https://user-images.githubusercontent.com/31449177/136833834-46c68afa-ea1a-42a9-88f0-6cd63951c4fd.png)

Need to discuss potential options. Should we send these inputs to the back-end, or the front-end could simply append them to the body itself. Thoughts? @kevincianfarini

**Comment by kevincianfarini** [comment]
I prefer to make the front-end as dumb as possible. We should allow the backend to handle the concatenation logic.

**Comment by kevincianfarini** [comment]
Want to schedule a meeting with Eliza?
