### ISSUE TITLE
Recording action events in the database

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#14]
The current `actions_raw` table is not suitable for recording changemaker actions since it's pretty closely coupled with the "I took action" google form input. For example, in the following table definition 

```
+-------------------+------------------------+-------------+-----------+----------------+-----------------------------------------------------------------+
| Column            | Type                   | Modifiers   | Storage   | Stats target   | Description                                                     |
|-------------------+------------------------+-------------+-----------+----------------+-----------------------------------------------------------------|
| email             | citext                 |             | extended  | <null>         | <null>                                                          |
| full_name         | character varying(256) |             | extended  | <null>         | <null>                                                          |
| date              | date                   |  not null   | plain     | <null>         | <null>                                                          |
| action            | action                 |  not null   | plain     | <null>         | <null>                                                          |
| intent            | action_intent          |  not null   | plain     | <null>         | <null>                                                          |
| count             | integer                |             | plain     | <null>         | Update the advocacy response form to allow only positive counts |
| source            | action_source          |  not null   | plain     | <null>         | <null>                                                          |
| audience          | audience               |             | plain     | <null>         | <null>                                                          |
| other_form_inputs | jsonb                  |             | extended  | <null>         | <null>                                                          |
| form_response_id  | character varying(256) |             | extended  | <null>         | <null>                                                          |
+-------------------+------------------------+-------------+-----------+----------------+-----------------------------------------------------------------+
```

we won't be collecting `full_name`, `form_response_id`, `other_form_inputs`, `audience`, and `source`. 

We have a couple of options to move forward. 

* Store `NULL` for the values that the action tool doesn't collect 
* Drop some of the columns that the action tool doesn't collect and use the same table. (Do we use `full_name` anyway?)
* Create a separate table for recording action tool events. I could see it looking like the following. 

| Table Name | Type | Modifier |
| --- | --- | ---|
| email | varchar | NOT NULL|
| action_type| <INITIATE_ACTION_FLOW, WRITE_WHY, WRITE_LEGISLATORS, CALL LEGISLATORS, TWEET_LEGISLATORS> | NOT NULL|
| timestamp | timestamptz | NOT NULL|

**Comment by mcchang** [comment]
Sorry for the delay @kevincianfarini.  Taking a look today

**Comment by mcchang** [comment]
@kevincianfarini I think creating a different table makes sense. The data is pretty different semantically and will probably diverge more and more from the google form data.

**Comment by kevincianfarini** [comment]
@mcchang How do you think we should structure the data? I think it might also make sense to have foreign keys to the several different types of actions changemakers can take. I need to think about this more, but if you have any ideas I'm here for them.

**Comment by kevincianfarini** [comment]
After more discussion, we decided it was best to track action in separate discrete tables. Those tables are as follows. 

# action_initiate

| email | initiated_at | 
| -- | -- |
| varchar | timestamptz|

# action_write_why

| email | wrote_at | 
| -- | -- |
| varchar | timestamptz|

# action_contact_legislator

| email | contacted_at | issue_id | bioguide_id | phone_contact_id | tweet_contact_id | action_network_contact_id | 
| -- | -- | -- | -- | -- | -- | -- |
| varchar | timestamptz| UUID Foreign Key | varchar | UUID Foreign Key Nullable | TBD nullable | TBD nullable| 

## phone_contact
| id | number_contacted | 
| -- | -- |
| UUID Primary Key | varchar |

**Comment by mcchang** [comment]
I'm going to work on proposing action tracking api endpoint(s)

**Comment by kevincianfarini** [comment]
Whats the reasoning?

**Comment by kevincianfarini** [comment]
The more I think about this, the more I think that contacting legislators should be split into separate tables as well. That would make it easier to add new forms of contact should they arise. 

### action_email_legislator

| email | contacted_at | issue_id | bioguide_id | action_network_id | 
| -- | -- | -- | -- | -- |
| varchar | timestamptz | bigint | varchar | TBD |

## action_tweet_legislator

| email | tweeted_at | issue_id | bioguide_id | tweet_id | 
| -- | -- | -- | -- | -- |
| varchar | timestamptz | bigint | varchar | TBD | 

## action_call_legislator

| email | called_at | issue_id | bioguide_id |  
| -- | -- | -- | -- |
| varchar | timestamptz | bigint | varchar | 


### Determining amount of contact

Because the big boon for this would be determining how many times a particular legislator is contacted across all forms of media, we could achieve that with some simple `UNION` statements. 

```sql
SELECT bioguide_id, COUNT(*)
FROM (
  SELECT bioguide_id FROM action_email_legislator
  UNION
  SELECT bioguide_id FROM action_tweet_legislator
  UNION
  SELECT bioguide_id FROM action_call_legislator
)
GROUP BY bioguide_id
```

The above is kind of psuedocode, but I think the idea is solid.

**Comment by mcchang** [comment]
Hm, not convinced that having each individual action type's table track email, timestamp, bioguide id and issue id is a good idea.

1. The analyst or programmer needs to figure out the domain of all action types (and their corresponding tables somehow), so I think it makes aggregating data harder for someone who does not already understand the schema. If there is just one actions table that has FK to action metadata tables, the aggregation query is simple and does not need to change if we add a new action type
2. If we wanted add a new common field for actions (imagine we have logged in users at some point and we want to key an action on a logged in user id), we'd need to add the same field to all of the action tables.

wdyt?

**Comment by kevincianfarini** [comment]
I agree. Rather than having an action table with multiple, possibly nullable, FK to metadata tables we should invert the relationship. Metadata entries should reference the main contact table. Something like the following. 

### action_contact_legislator
| id | email | contacted_at | issue_id | bioguide_id |
| -- | -- | -- | -- | -- | 
| bigserial | varchar | timestamptz| UUID Foreign Key | varchar |

### action_email_metadata

| action_contact_legislator_id | action_network_id |
| -- | -- |
| bigint FK | TBD |

### action_tweet_metadata

| action_contact_legislator_id | tweet_id |
| -- | -- |
| bigint FK | TBD |

### action_call_metadata


| action_contact_legislator_id | phone_number_called |
| -- | -- |
| bigint FK | varchar |


Reason being -- I found it error prone that an `action_contact` entry could have only one valid FK to another table, but has the possibility to have multiple. Adding constraints which enforces this feels clumsy Adding new action types would require a back fill, which seems unnecessary.

**Comment by kevincianfarini** [comment]
@mcchang let me know what you think!

**Comment by mcchang** [comment]
@kevincianfarini nice! I think we actually need FKs both ways (`action_email_legislator` to the detail tables and from the detail tables back to `action_email_legislator`) to truly model a one-to-one relationship. Otherwise the relationship is actually one-to-many.  

I don't think the constraint on the `action_contact_legislator` is too hard to implement and update when needed.  Something like https://www.db-fiddle.com/f/9qKFJ8x8FAuFnMRetBe2Wd/0, which we can update whenever we need to add a new separate action table.

![image](https://user-images.githubusercontent.com/66332/133553582-86678abd-ad45-4db4-ba18-262b3f3d833a.png)

**Comment by mcchang** [comment]
A couple of other comments on the schema
- We should use [postgres identity columns](https://www.postgresqltutorial.com/postgresql-identity-column/) instead of serial/bigserial for autoincrementing columns to avoid [weird issues](https://wiki.postgresql.org/wiki/Don%27t_D)
- For data validation it would be nice to ingest the current set of bioguide ids (and associated legislator attriburtes) into the database.  I can create an issue for that

**Comment by kevincianfarini** [comment]
totally down to use identity columns. I'll file an issue for the one-to-one relationship and get to it at a later date. I don't think it's pressing right now, but I definitely don't want it to slip through the cracks.

**Comment by kevincianfarini** [comment]
#74 and #75 are the remaining parts of this issue. I'm going to close for now since we have a much better idea of how to handle this problem.
