### ISSUE TITLE
Sections have incorrect descriptions 

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#175]
![image](https://user-images.githubusercontent.com/13242326/142696771-e9200e5c-ca44-4403-a21e-2062bc4d32ad.png)

![image](https://user-images.githubusercontent.com/13242326/142696810-410e7bc4-a882-465a-b990-006e2a1be34a.png)

Both of the above sections have incorrect section descriptions and guidance.

**Comment by jacknugent** [comment]
Should the descriptions just be swapped, or is there a copy somewhere I need to add?

**Comment by kevincianfarini** [comment]
For the email section it should be: 

> Fill out the form below to open up an email to your elected representatives. You can use our prompts to guide your through the process, or draft your own from scratch. 

For the call section: 

> Plan your personalized script (the field below is a working space for you!), and then click below to make your calls. You're the expert on your own experience and your own climate concern. Your advocacy is most effective when you speak from your unique perspective, so bring in personal details and anecdotes. 

It looks like the designs are lacking a description for the post on social media section. I will raise it with stakeholders.

**Comment by kevincianfarini** [comment]
@jacknugent description for social

> Social media can be very effective at grabbing the attention of policymakers and amplifying your message to a wider audience. Use the sample Tweet below as a starting point and don’t forget to tag your members of Congress!

**Comment by jacknugent** [comment]
In the future, we could (should?) have these paragraphs in the CMS so stakeholders can change them whenever they want -- thoughts?

**Comment by kevincianfarini** [comment]
Definitely. Open an issue?
