### ISSUE TITLE
Front-end hardcodes proxy for back-end

### ISSUE THREAD

**Issue by jacknugent** [climatechangemakers/climate-changemakers-act#18]
In package.json, we set the proxy like this:
```
"proxy": "http://backend:8080",
```

We should be using something like [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) to make this depend on an environment variable, as the [create react docs]() suggest, but there seems to be a bug where the path doesn't get appended when proxying, so all requests get rerouted to `http://backend:8080` instead of `http://backend:8080/api/endpointxyz`. 

I reported this bug in the [create-react-app repo](https://github.com/facebook/create-react-app/issues/11328) and the [http-proxy-middleware repo](https://github.com/chimurai/http-proxy-middleware/issues/656). For now, we will hardcode the proxy. Down the line, we can either see if this issue gets resolved or find some other way to proxy based on environment variable.

**Comment by kevincianfarini** [comment]
I believe this is a non-issue since we're going to be service pre-built static assets.
