### ISSUE TITLE
Figure out automatic deployment to AWS

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#22]

**Comment by kevincianfarini** [comment]
We should consider using [AWS ECS Fargate](https://aws.amazon.com/fargate/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc&fargate-blogs.sort-by=item.additionalFields.createdDate&fargate-blogs.sort-order=desc). It will allow us to flexibly pay based on how much compute and memory we use. Inspecting the current characteristics of our backend container yields the following results.  

```shell
$ docker ps -q | xargs docker stats

CONTAINER ID   NAME                                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
7faf81c2d743   climate-changemakers-act_backend_1    0.05%     419MiB / 23.33GiB     1.75%     56.7kB / 38.8kB   22.2MB / 0B       34
```

Upon originally launching the instance, we sit at around 100MiB of memory usage. It spikes to ~400MiB when the service receives the first requests. After that, it remains fairly constant. For this reason, I believe that memory will be the dominating cost center in AWS for us. 

I can research garbage collection and memory relinquishing strategies that the JVM offers and see if any of those help.

**Comment by mcchang** [comment]
Happy to help set this up - I've used fargate in the past before.  How much are we paying right now on (Heroku?)

**Comment by kevincianfarini** [comment]
@mcchang I'm not sure, I imagine were on the free plan. I think generally our rollout should look like this

* upgrade to latest stable JDK, which has some serious and aggressive garbage collections improvements. 
* serve static pre-built frontend content from Ktor. 
* Use a CDN to cache static content to avoid ECS costs for serving simple files. 

  * consider doing the same for simple GET requests like the current issue list? We could use a 5 minute TTL.

**Comment by mcchang** [comment]
Any reason we shouldn't put the Changemakers Act JS on S3/Cloudfront? (perhaps that's what you mean by bullet point 3, not sure).  I'm down to jump on a quick call in the next couple of days if you're free to talk through a plan if it might be easier! https://calendly.com/michaelychang/30min

**Comment by kevincianfarini** [comment]
That is what I meant by bullet 3. We would have the originating service be the ECS container and cache it in Cloudfront. 

I could also be convinced that storing the static assets in S3 is the right move. The only reason I'd prefer to have the originating service be the ECS container is that I'd also like to cache whatever the current issue list is in cloudfront, so it seems more sane to have both of those components live in the same place.

**Comment by mcchang** [comment]
@kevincianfarini I will take a look at how cloudfront <> ECS caching could work

**Comment by mcchang** [comment]
@kevincianfarini Is it cool if I unassign you from this task? I think having a single owner for a task makes it more clear who is responsible for next steps

**Comment by mcchang** [comment]
Before going down too far down this path, I am going to sync with Eliza about what the budget for this tool can and should be

**Comment by kevincianfarini** [comment]
Sounds good!

**Comment by kevincianfarini** [comment]
Closed via milestone 3

https://github.com/climatechangemakers/climate-changemakers-act/milestone/3
