### ISSUE TITLE
Airtable showing a lot of request data 

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#224]
I took a look at the logs today, and it seems like something is awry causing endless requests to AirTable. Based on the time distribution of these requests, I highly doubt its origination is from the backend.

![image](https://user-images.githubusercontent.com/13242326/146632935-9a139ed3-1b99-4359-8a93-0fc5fc6b718d.png)

I will research this more tomorrow. I suspect this has something to do with the frontend.

**Comment by kevincianfarini** [comment]
I'm noticing every time switch between browser tabs, a new set of requests gets kicked off. The following is a record of the requests this happens for. 

![image](https://user-images.githubusercontent.com/13242326/146650979-82fbf7fc-14ba-45e2-b9f2-2dbd8fef33f7.png)

**Comment by jacknugent** [comment]
This is because SWR defaults to being more liberal with GET requests. I'll make it more restrictive
