### ISSUE TITLE
Figure out production methodology 

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#23]
We need several accompanying issues to be solved before we can mark this as done. 

* #19 
* A working CI Solution 

  * #20
  * #21
* #22

**Comment by mcchang** [comment]
Here's my proposal for a first version of a production deployment, whenever we are ready for it.

![mermaid-diagram-20210919145154](https://user-images.githubusercontent.com/66332/134140387-4155fbd1-3fe5-476d-9f42-8cbe633e22e2.png)

I’m spending some time figuring out different ways to deploy our frontend and backend with an emphasis on

- free or very low cost
- continuous deployment from Git
- easy rollbacks to previous versions
- allowing more than one collaborator to login to deploy or debug the service

## Details:
### Frontend
* Hosting: As a service on [render.com](https://render.com)
* Cost: [Free](https://render.com/pricing/)
* What we get![image](https://user-images.githubusercontent.com/66332/134142169-78ec4ead-8f27-4f4e-8167-aa9aacbfeb91.png) (See https://render.com/docs/static-sites#static-sites)
### Backend
* Hosting: As a service on [render.com](https://render.com)
* Cost: [$7/month](https://render.com/pricing/#services)
* What we get![image](https://user-images.githubusercontent.com/66332/134142607-4ee8c77f-47a6-4aa9-810b-bb0f5ac5825f.png) (See https://render.com/pricing/#services)

Let me know what you think! Happy to schedule some time to chat about other potential implementations. @jacknugent @kevincianfarini I added you as collaborators to the render.com team if you want to poke around

**Comment by kevincianfarini** [comment]
@mcchang I love this outline! I have two possible concerns. 

I've been playing with `onrender`. The links commented in on PR builds are fully functional instances. When searching for my representatives, the request takes 6.45s, which is quite slow. The `issues` endpoint is also fairly slow clocking in around 2s. 

What is the scaling story for render? One of the nice things I've grown accustom to with AWS is the ability to quickly scale a container's resources up or down. From what I'm reading, Render's pricing seems to be more discrete buckets. 

Comparing Render's pricing ($7/month) with AWS's pricing for a similar setup (.25 vCPU, .5GB Memory; $8.89/month), I wonder if AWS ease of scaling and integration with other services is worth the extra $1.89? I'd be interested to see how this backend service performs on the lowest tier AWS ECS offering, too. If it's similar to Render's performance (6.45s for some requests), then definitely going with the cheaper option makes sense. 

Have we considered moving cloud platform providers altogether? I wonder if GCP or Azure offer a free year of service similar to AWS for some offerings. We're about expire our free year for RDS, so it might be worth migrating.

**Comment by mcchang** [comment]
Weird, doesn't seem to take that long for me. I could try deploying to ECS to see if things are drastically better. The networking between an ECS instance and our RDS instance must be faster.  I'm not sure how much faster though.

![image](https://user-images.githubusercontent.com/66332/134276552-9109cbf9-017e-4462-9f36-9dd1c71c1a9b.png)

> @mcchang I love this outline! I have two possible concerns.
> 
> I've been playing with `onrender`. The links commented in on PR builds are fully functional instances. When searching for my representatives, the request takes 6.45s, which is quite slow. The `issues` endpoint is also fairly slow clocking in around 2s.
> 
> What is the scaling story for render? One of the nice things I've grown accustom to with AWS is the ability to quickly scale a container's resources up or down. From what I'm reading, Render's pricing seems to be more discrete buckets.

Looks like we can [manually specify the number of instances we want or turn on autoscaling based on cpu + memory usage](https://render.com/docs/scaling). Fargate autoscaling is similar but slightly more flexible(manual + autoscaling based on cloudwatch metrics).  If we want to optimize for not worrying about scaling infrastructure, I think we should scale based on # of smaller containers as opposed to figuring out sizing for one specific instance.
> 
> Comparing Render's pricing ($7/month) with AWS's pricing for a similar setup (.25 vCPU, .5GB Memory; $8.89/month), I wonder if AWS ease of scaling and integration with other services is worth the extra $1.89? I'd be interested to see how this backend service performs on the lowest tier AWS ECS offering, too. If it's similar to Render's performance (6.45s for some requests), then definitely going with the cheaper option makes sense.
> 
> Have we considered moving cloud platform providers altogether? I wonder if GCP or Azure offer a free year of service similar to AWS for some offerings. We're about expire our free year for RDS, so it might be worth migrating.

We haven't considered switching.
