### ISSUE TITLE
Failed bioguide IDs not being respected when email delivery fails 

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#285]
In development, when I try to send an email and one of the recipient fails, I would expect retries only be conducted for the failed bioguide. Instead, I'm seeing that the `failedBioguideIds` in the error response body aren't respected. For example, this is the result of a single send email attempt which fails. 

```
postgres@0:postgres> select * from action_contact_legislator;
+------+---------+-------------------------------+------------+-------------------------+
| id   | email   | contacted_at                  | issue_id   | contacted_bioguide_id   |
|------+---------+-------------------------------+------------+-------------------------|
| 1    | k@c.com | 2022-02-10 01:55:19.674162+00 | 7          | K000384                 |
| 3    | k@c.com | 2022-02-10 01:55:29.607386+00 | 7          | W000805                 |
| 4    | k@c.com | 2022-02-10 01:55:29.649851+00 | 7          | K000384                 |
| 5    | k@c.com | 2022-02-10 01:55:39.641468+00 | 7          | K000384                 |
| 6    | k@c.com | 2022-02-10 01:55:39.641737+00 | 7          | W000805                 |
| 7    | k@c.com | 2022-02-10 01:55:49.588589+00 | 7          | K000384                 |
| 8    | k@c.com | 2022-02-10 01:55:49.616595+00 | 7          | W000805                 |
| 2    | k@c.com | 2022-02-10 01:55:19.674471+00 | 7          | W000805                 |
+------+---------+-------------------------------+------------+-------------------------+
```

**Comment by jacknugent** [comment]
Can you provide some more details so I can recreate this? As in a scenario where only one recipient fails

**Comment by kevincianfarini** [comment]
In development, none of our home IP addresses are whitelisted by the congressional house. Every request to send an email from a dev box should fail for the time being. 

I reproduced this just using the gui at localhost.

**Comment by kevincianfarini** [comment]
>Also, what is our expected behavior if an email fails? Retry three times?

That's correct

**Comment by jacknugent** [comment]
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/31449177/153327038-3aff41e5-cba9-492d-ae80-c8389f671007.png">
I see 4 `send-email` attempts (1 initial attempt and 3 retries) which all pass in the same 3 `contactedBioguideIds`

**Comment by kevincianfarini** [comment]
yes that's the issue. It should only be passing in bioguide ids on subsequent requests that are returned in the error body's `failedBioguideIds`. 

It's likely only your house member because of the whitelist ip thing.

**Comment by jacknugent** [comment]
I still don't understand what is wrong. 

I do the initial request with all three ids:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31449177/153491463-e78e96d5-ff8d-48fe-b279-d63647881cbb.png">
Get back an error response with all three ids failing, as expected:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/31449177/153491163-2ada27a6-7bcd-4bc5-94c9-7a0d10dbd4ad.png">
So, we retry the send-email and pass in those three ids returned from the previous error body's `failedBioguideIds`:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31449177/153491355-ccfc4c08-1ecc-4431-9898-090682ca03ea.png">

**Comment by kevincianfarini** [comment]
>Get back an error response with all three ids failing, as expected because of ip issue:

This is surprising to me. Only the House members are subject to the IP whitelist. The Senate side doesn't care. I'd expect only one of your emails to fail, and therefore the `failedBioguideIds` to only contain a single entry. 

I'm happy to screen share with you what I'm seeing offline.
