### ISSUE TITLE
Model issues data in our database

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#50]
Several tables will be involved which allows us to: 
1. track a ledger of focus issues, past and present 
2. track a list of issues
3. add, alter, and remove their talking points 

These three tables will be _read only_ from the perspective of the action tool. The desired end state will include a separate CMS service which will allow our policy experts to update, add, and focus issues. 

# The Issue Table

| id| title |
| -- | -- |
| UUID| varechar|

# The Talking Point Table

| id | title | issue_id | content |
| -- | -- | -- | -- |
| UUID | varchar | UUID Foreign Key | varchar, markdown compliant |

# The Focus Issue Ledger

| issue_id | focused_at | 
| -- | -- |
| UUID Foreign Key | timestamptz|

To get the current focus issue, select the most recently focused issue by `focused_at` descending.

**Comment by kevincianfarini** [comment]
One thing to note is how a future CMS integration would model the focus ledger.

**Comment by jacknugent** [comment]
As noted [here](https://github.com/climatechangemakers/climate-changemakers-act/pull/54/files/4a4f580092278713e5d4c0c0154d3bb4520a8265#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655), the `content` should probably be HTML compliant, not markdown compliant, because that's how all the CMS' I've worked with deliver rich text.

**Comment by kevincianfarini** [comment]
I think that should be an implementation detail of the API layer. That way we can swap out to whatever format we need, while the frontend consistently gets HTML.

**Comment by jacknugent** [comment]
Agreed. Right now the mocked API is Markdown.

**Comment by jacknugent** [comment]
Agreed. Right now the mock data for talking points is HTML and markdown syntax. I think it's overkill to support markdown and HTML in the mock data if all CMS solutions will just return HTML.
