### ISSUE TITLE
Stabilize `send-email` API contract

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#56]
I'm thinking the endpoint could look something like the following. 

```typescript
POST /api/send-email

{
  "relatedIssueId": int, // the issue a changemaker is writing their legislators about
  "emailBody": string,
  "contactedBioguideIds": string[] // the list of legislators the email is being sent to
}
```

**Comment by kevincianfarini** [comment]
@jacknugent mind chiming in about this?

**Comment by jacknugent** [comment]
Makes sense to me, what will it return?

**Comment by kevincianfarini** [comment]
It will return `204 No Content` if successful, otherwise it will give an HTTP error.

**Comment by kevincianfarini** [comment]
It's possible this endpoint will evolve more once we flesh out the action network stuff. I'm going to leave this open for now.

**Comment by kevincianfarini** [comment]
@jacknugent @EvanHahn 

Based on #102 in its current form, the request will look like the following (in cURL)

```sh
curl --location --request POST 'http://localhost:8080/api/send-email' \
--header 'Content-Type: application/json' \
--data-raw '{
    "originatingEmailAddress": "kevincianfarini@gmail.com",
    "title": "Mr.",
    "firstName": "Kevin",
    "lastName": "Cianfarini",
    "streetAddress": "123 Main Street",
    "city": "Richmond",
    "state": "VA",
    "postalCode": "23223",
    "relatedIssueId": 6,
    "emailSubject": "The email subject",
    "emailBody": "This is an email",
    "relatedTopics": ["Energy"],
    "contactedBioguideIds": ["hello", "goodbye"]
}'
```
currently, we're not validating bioguide ids. There's a separate issue #103 for this, which is why this request currently works with "hello" and "goodbye". This will not work in the future.
