### ISSUE TITLE
Stabilize `record-call` endpoint

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#64]
I'm thinking the request could be something like the following. 

```js
POST /api/record-call

{
  "originatingEmail": string,
  "relatedIssueId": int,
  "contactedBioguideId": string,
  "phoneNumberCalled": string
}
```

I don't know if we'd rather have this endpoint handle multiple phone calls at once, or if we should handle them in isolation. The email endpoint handled all legislators at once, but that's because a single email is sent to all lawmakers.

**Comment by kevincianfarini** [comment]
@jacknugent let me know what you think

**Comment by jacknugent** [comment]
I think handling each call in isolation makes more sense. There might be cases where a user does not finish all their calls. A user might give up halfway, or their internet goes out. In those cases, if we recorded the calls in isolation, we would still know the incomplete number of calls the user made.
