### ISSUE TITLE
Add "Who to Call" data to `initiate-action` endpoint

### ISSUE THREAD

**Issue by jacknugent** [climatechangemakers/climate-changemakers-act#66]
Screenshot from [most recent design](https://www.figma.com/file/PEEkfIkziGfLogDHxSex9K/CC-%2F%2F-Action-Tool?node-id=205%3A2):
![image](https://user-images.githubusercontent.com/31449177/133623322-1d831038-d492-451b-bbbe-44329da9db38.png)

Looks like the front-end will need the following info for each representative:
- Who to call
- DC Office number
- Local Office number

Would make sense to add this onto `initiate-action` endpoint. @kevincianfarini thoughts? Not sure where this data lives, or if there can be more than 2 numbers to call for each representative.

**Comment by kevincianfarini** [comment]
So we currently have a phone number for each senator/rep. We only have one: the DC office phone number. I wonder if that could suffice? It's a question to ask for sure.

**Comment by kevincianfarini** [comment]
```js
    "legislators": [
        {
            "name": "A. McEachin",
            "role": "representative",
            "siteUrl": "https://mceachin.house.gov",
            "phone": "202-225-6365",
            "imageUrl": "https://bioguide.congress.gov/bioguide/photo/M/M001200.jpg",
            "area": {
                "state": "VA",
                "districtNumber": 4
            },
```

**Comment by kevincianfarini** [comment]
To get a list of district office phone numbers, I think we're going to need to parse the data offered by @unitedstates here. https://github.com/unitedstates/congress-legislators/blob/main/legislators-district-offices.yaml 

We could include this data in our database and update it periodically. I'll try and find if there's an API to abstract this away from us, though. I don't want us to have to maintain this.

**Comment by kevincianfarini** [comment]
We probably also need to do some calculations for how far away a certain district office is from the users. We get lat and long of the input address back from geocodio. The US project also includes lat/long of all district offices (and their phone numbers). 

Unfortunately, since places are redistricted so often, they don't include district numbers. 


For example, here's the first list of offices for a single bioguide id. 

| bioguide | thomas | govtrack | id | address | building | city | fax | hours | phone | state | suite | zip | latitude | longitude |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| A000055|01460|400004|A000055-cullman|205 4th Ave. NE| | Cullman | 256-737-0885 || 256-734-6043 |AL|Suite 104|35055|34.181059|-86.840631 |
| A000055|01460|400004|A000055-gadsden|600 Broad St.||Gadsden|256-546-8778||256-546-0201|AL|Suite 107|35901|34.01421000000001|-86.006846 |
| A000055|01460|400004|A000055-jasper|1710 Alabama Ave.|Carl Elliott Building|Jasper|205-221-9035||205-221-2310|AL|247|35501|33.83438|-87.274935 |

**Comment by kevincianfarini** [comment]
I'm looking through the data now. It appears that the @unitedstates project doesn't guarantee a district office entry has a phone number, nor that it has a lat/long. For example, here are two choice entries (some information is omitted). 

| bioguide_id | phone | lat | long |
| -- | -- | -- | -- |
| T000474 |   | 34.0993394 | -117.3721013
| K000395 | 570-374-9469 |   | 

So, I think this is going to require an API change. The phone number for a member of congress (MoC) is going to become a list. 

```js
    "legislators": [
        {
            "name": "A. McEachin",
            "role": "representative",
            "siteUrl": "https://mceachin.house.gov",
            "phoneNumbers":  [
                "202-225-6365",
                "804-867-5309"
             ],
            "imageUrl": "https://bioguide.congress.gov/bioguide/photo/M/M001200.jpg",
            "area": {
                "state": "VA",
                "districtNumber": 4
            },
```

We should display every phone number is that list as an option to call. It will contain a maximum of 2 entries -- one for the DC office and one for the local district office. We might need to consider the case where a legislator has no phone numbers. 

There are 3 distinct cases when trying to choose a district office phone number to return. 

1. A district office entry has both phone and lat/long
2. A district office has a lat/long, but no phone
3. A district office has phone, but no lat/long. 

For the happy path where we have all of the information we need, we should sort the list by distance from the user and select the closest one. 

```kotlin
value class Location(lat: Double, long: Double)

fun getClosestDistrictOffice(requestingLocation: Location): DistrictOffice? {
  return myListOfDistrictOffices.sortedBy { it.distanceFrom(requestingLocation) }.firstOrNull()
}

fun Location.distanceFrom(other: Location): Double = TODO()
```

I think in case 2, we can just omit those entries. 

```kotlin
val districtOfficesWithPhoneNumbers = districtOffices.filter { it.phoneNumber != null }
```

In case 3, we should only fall back to that if there were no district offices to choose from with a lat/long. 

```kotlin
fun getClosestDistrictOffice(requestingLocation: Location): DistrictOffice? {
  val closestOffice = myListOfDistrictOffices.filter { it.location != null }.sortedBy { it.distanceFrom(requestingLocation) }.firstOrNull()
  return closestOffice ?: myListOfDistrictOffices.filter { it.phone != null }.firstOrNull()
}
```
