### ISSUE TITLE
States appear in two places

### ISSUE THREAD

**Issue by jacknugent** [climatechangemakers/climate-changemakers-act#78]
Currently, the front-end and back-end each have their own hard-coded list of the 50 United States + territories. This design may confuse future developers, and may make State bugs/typos harder to find. Opening discussion to decide if creating one master list of the States is worth it, and what our options are.

**Comment by kevincianfarini** [comment]
Which API structure would you prefer? 

```js
[ "VA", "WV", "NJ" .... ]
```

or 

```js
[
  { abbreviation: "VA", name: "Virginia" },
  ...
  { abbreviation: "WV", name: "West Virginia" }
]
```

The first one is easy and requires no extra work. The second one is slightly more difficult, and would require a change to how we're serializing these values.

**Comment by jacknugent** [comment]
Full-state name is a better experience, but maybe not the end of the world
